### ISSUE TITLE
v0.1.0 raises IndexError during login

### ISSUE THREAD

**Issue by j9brown** [RobertD502/home-assistant-iocare#10]
The Coway integration isn't working for me anymore after upgrading to v0.1.0: it raises an IndexError on startup.  So I tried disabling and re-adding the integration and it produced a similar IndexError as shown below.

---

```
This error originated from a custom integration.

Logger: custom_components.coway
Source: custom_components/coway/coordinator.py:77
Integration: Coway IoCare (documentation, issues)
First occurred: 2:39:08 AM (10 occurrences)
Last logged: 2:48:33 AM

Unexpected error fetching coway data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/coway/coordinator.py", line 77, in _async_update_data
    data = await self.client.async_get_purifiers_data()
  File "/usr/local/lib/python3.10/site-packages/cowayaio/coway_client.py", line 139, in async_get_purifiers_data
    data = await self.async_get_purifiers()
  File "/usr/local/lib/python3.10/site-packages/cowayaio/coway_client.py", line 120, in async_get_purifiers
    await self.login()
  File "/usr/local/lib/python3.10/site-packages/cowayaio/coway_client.py", line 48, in login
    state_id = await self._get_state_id()
  File "/usr/local/lib/python3.10/site-packages/cowayaio/coway_client.py", line 61, in _get_state_id
    state = response.url.query_string.split('state=',1)[1]
IndexError: list index out of range
```

---

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/coway/util.py:25
Integration: Coway IoCare (documentation, issues)
First occurred: 2:45:41 AM (3 occurrences)
Last logged: 2:49:03 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 178, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/coway/config_flow.py", line 92, in async_step_user
    access_token, refresh_token = await async_validate_api(self.hass, username, password)
  File "/config/custom_components/coway/util.py", line 25, in async_validate_api
    coway_query = await client.async_get_purifiers()
  File "/usr/local/lib/python3.10/site-packages/cowayaio/coway_client.py", line 120, in async_get_purifiers
    await self.login()
  File "/usr/local/lib/python3.10/site-packages/cowayaio/coway_client.py", line 48, in login
    state_id = await self._get_state_id()
  File "/usr/local/lib/python3.10/site-packages/cowayaio/coway_client.py", line 61, in _get_state_id
    state = response.url.query_string.split('state=',1)[1]
IndexError: list index out of range
```

**Comment by RobertD502** [comment]
Temporary fix:
Add the integration and once you get the index error disregard it. Then restart Home Assistant. It should work after that.

When adding the integration, the config flow checks to see if the account is valid which requires logging in. Then Home Assistant starts the coordinator which also requires being authenticated with Coway's servers. 

Coway's servers don't like the back to back logins so I had implemented a reuse of the access token during first time setups and tested it extensively to avoid this problem, so, I'm surprised it came up for you.

When you restart Home Assistant, this time only the coordinator logs into your account and the error won't come up again.

**Comment by j9brown** [comment]
How strange!  I was running 0.0.3.4 then updated to 0.1.0 and encountered this error.  Then I disabled the integration, restarted and tried to add the integration again and encountered this error again.  And just now, I re-enabled the integration and restarted and everything seems to work fine.  Huh.

**Comment by RobertD502** [comment]
That is pretty odd...since you were updating to 0.1.0, and after restarting, all that happens during the first reboot is your config entry gets migrated to a new version followed by the coordinator initializing. So, the problem shouldn't occur given that only the coordinator is logging in and not both the coordinator and the config flow.

When you say you disabled the integration then re-added it, are you saying you disabled the integration, restarted HA, and then re-enabled it or are you saying you deleted it, restarted HA, and then re-added the integration?

If you went the disable/re-enable path instead of the delete/re-add path, I'm assuming something funky happened during the update and the config flow ran in addition to the coordinator. As a result, disabling/re-enabling just restarted the same process over again.

Regardless, I'm glad you're back up and running. I'll leave this issue open for the next couple of days as others start updating to 0.1.0 / in case they happen to run into this issue.

**Comment by RobertD502** [comment]
@j9brown 
Just pushed out version `0.1.1` that uses a single CowayClient instance instead of passing around the initial access and refresh token between CowayClient objects. That should eliminate the possibility of this happening again.
